In [1]:
import numpy as np

In [10]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [12]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [13]:
a.shape

(5,)

In [16]:
a.ndim

1

In [19]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
a = np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.diag(a)

array([1., 1., 1.])

In [27]:
b = np.diag([1,2,3,4])
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [29]:
np.random.rand(4) #uniform distribution

array([0.99376384, 0.44823916, 0.6749328 , 0.55354633])

In [31]:
np.random.randn(4) #gausian distribution

array([-0.5627788 ,  0.37866315,  0.33914453,  2.75265836])

In [40]:
b = np.array([1,2,2])
print(b.dtype)
b

int32


array([1, 2, 2])

In [41]:
np.shares_memory(a,b)

False

# Fancy indexing

In [58]:
a = np.random.randint(1,12,10)
a

array([10,  8,  7,  8, 10,  6,  6,  1, 11,  4])

In [59]:
mask = (a%2==0)
mask

array([ True,  True, False,  True,  True,  True,  True, False, False,
        True])

In [60]:
extract_data = a[mask]
extract_data

array([10,  8,  8, 10,  6,  6,  4])

convert even places to nagative 

In [68]:
a[mask] = -1
a

array([-1, -1,  7, -1, -1, -1, -1,  1, 11, -1])

In [73]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [71]:
a*b

array([[ 1,  4],
       [ 9, 16]])

In [72]:
a.dot(b)

array([[ 7, 10],
       [15, 22]])

In [82]:
a = np.array([[1,2,3],[1,2,3]])
b = np.array([1,2,3])
a+b

array([[2, 4, 6],
       [2, 4, 6]])